spring:
  application.name : simpleBatch tasklet
  datasource:
    url: "jdbc:postgresql://127.0.0.1:31001/postgres"
    username: sample
    password: sample
    driver-class-name: org.postgresql.Driver
    embedded-directory: target
    initialization-mode: always
    hikari:
      maximum-pool-size: 4
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  batch:
    initialize-schema: always
    job:
      enabled: true #어플리케이션 구동시 컨텍스트 내의 모든 스프링 배치 작업 자동 실행 여부(false로 해야 구동시 무조건 실행이 안됨)

mybatis:
  type-aliases-package : com.batchdev.myBatisTest.model # 패키지 명을 생략할 수 있도록 alias 설정
  mapper-locations: classpath:mybatis-mapper/*.xml
  configuration:
    default-fetch-size: 100
    lazyLoadingEnabled : true
    aggressiveLazyLoading : false
    mapUnderscoreToCamelCase : true  # model 프로퍼티 camel case 설정

logging:
  level.org.springframework.cloud.task : debug
  level.org.springframework.batch: debug